void InitColors(WINDOW *win);
void InitRettangle(Rettangle *r, int x1, int y1, int x2, int y2);
void DrawOnlyAngles (Rettangle table);
void DrawRettangle (Rettangle table);
int ChooseColor();
void WriteScore(int n);
void WriteLife(int life);
void WriteLegend();
void WriteLevel(int level);
void DrawSpaceship(int y, int x);
void DeleteSpaceship(int y, int x);
void DrawSpacecraft(int y, int x, char name[], int level, int life);
void DeleteSpacecraft(int y, int x, int size);
void DrawRocks(int y, int x, int life);
void DeleteRocks(int y, int x);
void DrawMissile(int y, int x);
void DeleteMissile(int y, int x);
void DrawBannerSPACE(int y, int x);
void DeleteBannerSPACE(int y, int x);
void DrawBannerINVADERS(int y, int x);
void DeleteBannerINVADERS(int y, int x);
void DrawGameTitle();
void ClearGameTable();
void YouWin();
void YouLose();
void InitBoard (WINDOW* gameWindow);
